name: github-Actions-CI
on: 
    push:
        branches:
            - main
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4