name: github-Actions-CI
on: 
    push:
        branches:
            - ci-aws
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: search and replace the auth key
              run: |
                ls
                export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vprofile --domain-owner 367065853931 --region ap-south-1 --query authorizationToken --output text`
                sed -i 's/${env.CODEARTIFACT_AUTH_TOKEN}/`echo $CODEARTIFACT_AUTH_TOKEN`/g' settings.xml